### ISSUE TITLE
Possible not complete installation documentation

### ISSUE THREAD

**Issue by alexdux** [QuantConnect/Lean.DataSource.AlphaVantage#11]
Trying to install it locally with Lean/ already installed, I encountered that it is not clear where to install this "plugin" relative to Lean. It is also not clear how to integrate and run it with Lean.
Could you clarify this point? Searching everywhere possible did not give anything.

Meaning locally downloading Lean and this "plugin" to patch it and do some minor tweaks.

#### Expected Behavior
Complete documentation on how to install and integrate it with Lean.

#### Actual Behavior
The method of integration with Lean is not clear.

#### Potential Solution
Please add details about the integration with Lean.

#### Reproducing the Problem
Always.

#### System Information

Linux + VSCode

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @alexdux! We suggest people to use the lean CLI or local platform, we don't give support for local installs due to the complexity of different environment setups. Can see more information about the lean CLI [here](https://www.quantconnect.com/docs/v2/lean-cli) and the local platform our vscode extension [here](https://www.quantconnect.com/docs/v2/local-platform)
